const env = import.meta.env;

export const {
  VITE_FIREBASE_API_KEY,
  VITE_FIREBASE_AUTH_DOMAIN,
  VITE_FIREBASE_PROJECT_ID,
  VITE_FIREBASE_STORAGE_BUCKET,
  VITE_FIREBASE_MESSAGING_SENDER_ID,
  VITE_FIREBASE_APP_ID,
  VITE_GOOGLE_API_URL,
  VITE_CLOUDFLARE_API_TOKEN,
  VITE_CLOUDFLARE_WORKER_URL,
} = env;
